// pdfRenderer.js
//
// PDF renderer for the lesson generator.
//
// IMPORTANT:
// Images generated by imageGenerator.js are stored under:
//   <project-root>/public/images_temp/
//
// But the lesson JSON stores them as web paths:
//   /images_temp/section_L1_introduction_xxx.png
//
// This renderer converts those web paths into REAL filesystem paths
// and embeds the images directly into the HTML as base64.
// This avoids Windows path/URL problems inside Puppeteer.

const fs = require('fs');
const path = require('path');
const puppeteer = require('puppeteer');


// ================================================================
// PATH CONFIGURATION
// ================================================================

const PROJECT_ROOT = __dirname;
const PUBLIC_DIR = path.join(PROJECT_ROOT, 'public');
const IMAGE_TEMP_DIR = path.join(PUBLIC_DIR, 'images_temp');


// ================================================================
// LOGGING
// ================================================================

function log(...args) {
  console.log('[pdfRenderer]', ...args);
}


// ================================================================
// IMAGE PATH RESOLVER
// ================================================================
//
// Accepts things like:
//
//   /images_temp/foo.png
//   images_temp/foo.png
//   \images_temp\foo.png
//   D:\leson\public\images_temp\foo.png
//   ./public/images_temp/foo.png
//
// Returns an actual filesystem path if it exists.
// Otherwise returns null.
//
// ================================================================

function resolveImagePath(imageSource) {
  if (!imageSource || typeof imageSource !== 'string') {
    return null;
  }

  let source = imageSource.trim();

  if (!source) {
    return null;
  }

  // --------------------------------------------------------------
  // 1. Remove query strings / hashes from URL-style paths
  // --------------------------------------------------------------

  source = source.split('?')[0].split('#')[0];

  // --------------------------------------------------------------
  // 2. Normalize slash direction
  // --------------------------------------------------------------

  source = source.replace(/\//g, path.sep);

  // --------------------------------------------------------------
  // 3. If it is already an existing absolute filesystem path
  // --------------------------------------------------------------

  if (path.isAbsolute(source)) {
    if (fs.existsSync(source)) {
      return source;
    }

    // On Windows, "/images_temp/foo.png" is considered absolute
    // but is NOT the path we want. Continue below.
  }

  // --------------------------------------------------------------
  // 4. Remove leading slashes
  //
  // "/images_temp/foo.png"
  // becomes
  // "images_temp/foo.png"
  // --------------------------------------------------------------

  let relativeSource = source.replace(/^[/\\]+/, '');

  // --------------------------------------------------------------
  // 5. Remove "public/" if it is already present
  //
  // public/images_temp/foo.png
  // becomes
  // images_temp/foo.png
  // --------------------------------------------------------------

  relativeSource = relativeSource.replace(
    /^public[/\\]+/i,
    ''
  );

  // --------------------------------------------------------------
  // 6. Remove "./"
  // --------------------------------------------------------------

  relativeSource = relativeSource.replace(
    /^\.[/\\]+/,
    ''
  );

  // --------------------------------------------------------------
  // 7. Candidate filesystem locations
  // --------------------------------------------------------------

  const candidates = [
    // Normal expected location:
    path.join(PUBLIC_DIR, relativeSource),

    // Specifically handle images_temp:
    path.join(IMAGE_TEMP_DIR, path.basename(relativeSource)),

    // Project root:
    path.join(PROJECT_ROOT, relativeSource),

    // Current working directory:
    path.join(process.cwd(), relativeSource),

    // CWD/public:
    path.join(process.cwd(), 'public', relativeSource),

    // CWD/public/images_temp:
    path.join(
      process.cwd(),
      'public',
      'images_temp',
      path.basename(relativeSource)
    )
  ];

  // --------------------------------------------------------------
  // 8. Return first existing file
  // --------------------------------------------------------------

  for (const candidate of candidates) {
    try {
      if (fs.existsSync(candidate)) {
        const stat = fs.statSync(candidate);

        if (stat.isFile()) {
          return path.normalize(candidate);
        }
      }
    } catch (_) {
      // Ignore invalid candidates and continue.
    }
  }

  return null;
}


// ================================================================
// IMAGE -> DATA URI
// ================================================================
//
// Embedding images directly into HTML is much more reliable with
// Puppeteer than asking Chromium to resolve local Windows paths.
//
// ================================================================

function imageToDataUri(imagePath) {
  if (!imagePath || !fs.existsSync(imagePath)) {
    return null;
  }

  try {
    const buffer = fs.readFileSync(imagePath);

    const ext = path
      .extname(imagePath)
      .toLowerCase();

    let mimeType = 'image/png';

    switch (ext) {
      case '.jpg':
      case '.jpeg':
        mimeType = 'image/jpeg';
        break;

      case '.webp':
        mimeType = 'image/webp';
        break;

      case '.gif':
        mimeType = 'image/gif';
        break;

      case '.svg':
        mimeType = 'image/svg+xml';
        break;

      case '.png':
      default:
        mimeType = 'image/png';
        break;
    }

    return `data:${mimeType};base64,${buffer.toString('base64')}`;
  } catch (err) {
    log(
      `❌ Failed to read image: ${imagePath}`,
      err.message
    );

    return null;
  }
}


// ================================================================
// ESCAPE HTML
// ================================================================

function escapeHtml(value) {
  if (value === null || value === undefined) {
    return '';
  }

  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}


// ================================================================
// MARKDOWN -> HTML
// ================================================================
//
// We use "marked" when available because the lesson content contains
// markdown formatting.
//
// Falls back to a lightweight renderer if marked isn't installed.
//
// ================================================================

let marked = null;

try {
  marked = require('marked');
} catch (_) {
  // marked isn't installed.
  // Fallback renderer below will be used.
}


// ================================================================
// FALLBACK MARKDOWN RENDERER
// ================================================================

function simpleMarkdownToHtml(markdown) {
  if (!markdown) {
    return '';
  }

  let html = escapeHtml(markdown);

  // Horizontal rules
  html = html.replace(
    /^---$/gm,
    '<hr>'
  );

  // Headings
  html = html.replace(
    /^###### (.+)$/gm,
    '<h6>$1</h6>'
  );

  html = html.replace(
    /^##### (.+)$/gm,
    '<h5>$1</h5>'
  );

  html = html.replace(
    /^#### (.+)$/gm,
    '<h4>$1</h4>'
  );

  html = html.replace(
    /^### (.+)$/gm,
    '<h3>$1</h3>'
  );

  html = html.replace(
    /^## (.+)$/gm,
    '<h2>$1</h2>'
  );

  html = html.replace(
    /^# (.+)$/gm,
    '<h1>$1</h1>'
  );

  // Bold
  html = html.replace(
    /\*\*(.+?)\*\*/g,
    '<strong>$1</strong>'
  );

  // Italic
  html = html.replace(
    /\*(.+?)\*/g,
    '<em>$1</em>'
  );

  // Inline code
  html = html.replace(
    /`([^`]+)`/g,
    '<code>$1</code>'
  );

  // Unordered lists
  html = html.replace(
    /^(?:-|\*) (.+)$/gm,
    '<li>$1</li>'
  );

  // Wrap consecutive li elements
  html = html.replace(
    /((?:<li>.*?<\/li>\s*)+)/gs,
    '<ul>$1</ul>'
  );

  // Ordered lists
  html = html.replace(
    /^(?:\d+)\. (.+)$/gm,
    '<li>$1</li>'
  );

  // Newlines
  html = html.replace(
    /\n{2,}/g,
    '</p><p>'
  );

  html = `<p>${html}</p>`;

  return html;
}


// ================================================================
// MARKDOWN TO HTML
// ================================================================

function markdownToHtml(markdown) {
  if (!markdown) {
    return '';
  }

  try {
    if (marked) {
      // Support both marked versions:
      //
      // marked.parse(...)
      //
      // and older:
      // marked(...)
      //

      if (typeof marked.parse === 'function') {
        return marked.parse(markdown);
      }

      if (typeof marked === 'function') {
        return marked(markdown);
      }
    }
  } catch (err) {
    log(
      '⚠️ Marked failed, using fallback markdown renderer:',
      err.message
    );
  }

  return simpleMarkdownToHtml(markdown);
}


// ================================================================
// PREPARE IMAGE
// ================================================================
//
// Takes the path from the JSON and turns it into:
//   data:image/png;base64,...
//
// ================================================================

function prepareImage(imageSource, lessonNum, sectionKey) {
  if (!imageSource) {
    log(
      `⚠️ No image source for Lesson ${lessonNum} / ${sectionKey}`
    );

    return null;
  }

  log(`Lesson ${lessonNum} / ${sectionKey}`);
  log(`Image source: ${imageSource}`);

  const resolvedPath = resolveImagePath(imageSource);

  log(
    `Resolved path: ${resolvedPath || '(NOT FOUND)'}`
  );

  if (!resolvedPath) {
    log(
      `❌ Could not resolve image file: ${imageSource}`
    );

    return null;
  }

  const exists = fs.existsSync(resolvedPath);

  log(`Exists: ${exists}`);

  if (!exists) {
    log(
      `❌ Image file does not exist: ${resolvedPath}`
    );

    return null;
  }

  try {
    const stat = fs.statSync(resolvedPath);

    log(
      `Image size: ${stat.size} bytes`
    );
  } catch (_) {}

  const dataUri = imageToDataUri(resolvedPath);

  if (!dataUri) {
    log(
      `❌ Could not convert image to data URI: ${resolvedPath}`
    );

    return null;
  }

  log(
    `✅ Image loaded successfully: ${path.basename(resolvedPath)}`
  );

  return dataUri;
}


// ================================================================
// BUILD LESSON HTML
// ================================================================

function buildLessonHtml(
  structure,
  generatedSections,
  images
) {
  const chapter = structure.chapter || {};
  const lessons = structure.lessons || [];

  let html = `
<!DOCTYPE html>
<html>
<head>

<meta charset="UTF-8">

<style>

@page {
  size: A4;
  margin: 16mm 15mm 18mm 15mm;
}

* {
  box-sizing: border-box;
}

body {
  font-family:
    Arial,
    "Segoe UI",
    sans-serif;

  color: #222;

  font-size: 10.5pt;

  line-height: 1.55;

  margin: 0;

  padding: 0;
}

h1 {
  font-size: 24pt;
  margin: 0 0 10px 0;
  color: #1A4D7A;
}

h2 {
  font-size: 18pt;
  margin-top: 24px;
  margin-bottom: 10px;
  color: #1A4D7A;

  border-bottom: 1px solid #D8E2EC;

  padding-bottom: 5px;
}

h3 {
  font-size: 14pt;
  margin-top: 18px;
  margin-bottom: 7px;
  color: #245B85;
}

h4 {
  font-size: 12pt;
  color: #333;
}

p {
  margin: 0 0 9px 0;
}

ul,
ol {
  margin-top: 5px;
  margin-bottom: 12px;
  padding-left: 22px;
}

li {
  margin-bottom: 4px;
}

strong {
  font-weight: 700;
}

code {
  background: #F1F3F5;
  padding: 2px 4px;
  border-radius: 3px;
}

hr {
  border: none;
  border-top: 1px solid #D9D9D9;
  margin: 18px 0;
}

.cover {
  min-height: 240mm;

  display: flex;

  flex-direction: column;

  justify-content: center;

  align-items: center;

  text-align: center;

  page-break-after: always;
}

.cover h1 {
  font-size: 30pt;
  margin-bottom: 15px;
}

.cover h2 {
  border: none;
  font-size: 20pt;
  margin: 0;
}

.cover-meta {
  margin-top: 30px;
  font-size: 13pt;
  color: #555;
}

.lesson {
  page-break-before: always;
}

.lesson:first-of-type {
  page-break-before: auto;
}

.lesson-header {
  padding-bottom: 12px;

  margin-bottom: 20px;

  border-bottom: 3px solid #1A4D7A;
}

.lesson-number {
  font-size: 11pt;
  font-weight: 700;
  color: #777;

  text-transform: uppercase;

  letter-spacing: 0.5px;

  margin-bottom: 4px;
}

.lesson-title {
  font-size: 25pt;
  font-weight: 700;
  color: #1A4D7A;
}

.lesson-description {
  margin-top: 8px;
  color: #555;
  font-size: 11pt;
}

.section {
  margin-top: 24px;

  page-break-inside: auto;
}

.section-title {
  font-size: 18pt;

  color: #1A4D7A;

  border-bottom: 1px solid #D8E2EC;

  padding-bottom: 5px;

  margin-bottom: 12px;
}

.section-image {
  display: block;

  width: 100%;

  max-width: 170mm;

  max-height: 85mm;

  object-fit: contain;

  margin: 12px auto 18px auto;

  page-break-inside: avoid;
}

.image-container {
  width: 100%;

  text-align: center;

  margin: 12px 0 18px 0;

  page-break-inside: avoid;
}

.slo-box {
  background: #F4F8FC;

  border-left: 4px solid #1A4D7A;

  padding: 10px 12px;

  margin: 15px 0;
}

.page-break {
  page-break-after: always;
}

table {
  border-collapse: collapse;

  width: 100%;

  margin: 12px 0;
}

th,
td {
  border: 1px solid #CCC;

  padding: 6px 8px;

  text-align: left;
}

th {
  background: #F0F4F8;
}

blockquote {
  border-left: 4px solid #AAA;

  margin-left: 0;

  padding-left: 12px;

  color: #555;
}

.math {
  font-family: "Times New Roman", serif;

  text-align: center;

  margin: 15px 0;
}

.footer {
  position: fixed;

  bottom: -8mm;

  left: 0;

  right: 0;

  text-align: center;

  font-size: 8pt;

  color: #888;
}

</style>

</head>

<body>
`;

  // ==============================================================
  // COVER
  // ==============================================================

  html += `
<div class="cover">

  <h1>${escapeHtml(
    chapter.title || 'Lesson Plan'
  )}</h1>

  <h2>
    Grade ${escapeHtml(
      chapter.grade || ''
    )}
  </h2>

  <div class="cover-meta">

    ${
      chapter.strand
        ? `<div>${escapeHtml(chapter.strand)}</div>`
        : ''
    }

    ${
      chapter.number !== undefined
        ? `<div>Chapter ${escapeHtml(chapter.number)}</div>`
        : ''
    }

  </div>

</div>
`;


  // ==============================================================
  // LESSONS
  // ==============================================================

  lessons.forEach((lesson, lessonIndex) => {

    const lessonSections =
      generatedSections[lessonIndex] ||
      generatedSections[lesson.number - 1] ||
      {};

    const lessonImages =
      images?.[lessonIndex] ||
      images?.[lesson.number - 1] ||
      {};

    html += `
<div class="lesson">

  <div class="lesson-header">

    <div class="lesson-number">
      Lesson ${escapeHtml(lesson.number)}
    </div>

    <div class="lesson-title">
      ${escapeHtml(lesson.title)}
    </div>

    ${
      lesson.description
        ? `
        <div class="lesson-description">
          ${escapeHtml(lesson.description)}
        </div>
        `
        : ''
    }

  </div>
`;

    // ------------------------------------------------------------
    // SLO BOX
    // ------------------------------------------------------------

    if (
      lesson.slos &&
      lesson.slos.length
    ) {

      html += `
<div class="slo-box">

  <strong>Student Learning Outcomes</strong>

  <ul>
`;

      lesson.slos.forEach(
        (slo, i) => {

          const description =
            lesson.slo_descriptions?.[i];

          html += `
<li>
  <strong>${escapeHtml(slo)}</strong>
  ${
    description
      ? ` — ${escapeHtml(description)}`
      : ''
  }
</li>
`;

        }
      );

      html += `
  </ul>

</div>
`;
    }


    // ------------------------------------------------------------
    // SECTION ORDER
    // ------------------------------------------------------------

    const sectionOrder = [
      ['introduction', 'Introduction'],
      ['warmUp', 'Warm-Up'],
      ['conceptBuilding', 'Concept Building'],
      ['examples', 'Worked Examples'],
      ['popUpQuiz', 'Pop-Up Quiz'],
      ['mentalMaths', 'Mental Maths'],
      ['practiceQuestions', 'Practice Questions'],
      ['keyTakeaways', 'Key Takeaways']
    ];


    // ------------------------------------------------------------
    // RENDER SECTIONS
    // ------------------------------------------------------------

    sectionOrder.forEach(
      ([sectionKey, sectionTitle]) => {

        const content =
          lessonSections[sectionKey];

        if (
          !content ||
          !String(content).trim()
        ) {
          return;
        }

        html += `
<div class="section">

  <div class="section-title">
    ${escapeHtml(sectionTitle)}
  </div>
`;

        // --------------------------------------------------------
        // IMAGE
        // --------------------------------------------------------

        const imageSource =
          lessonImages[sectionKey];

        if (imageSource) {

          const dataUri =
            prepareImage(
              imageSource,
              lesson.number,
              sectionKey
            );

          if (dataUri) {

            html += `
<div class="image-container">

  <img
    class="section-image"
    src="${dataUri}"
    alt="${escapeHtml(sectionTitle)} illustration"
  />

</div>
`;

          } else {

            log(
              `⚠️ Skipping image for Lesson ${lesson.number} / ${sectionKey}`
            );

          }

        } else {

          log(
            `ℹ️ No image registered for Lesson ${lesson.number} / ${sectionKey}`
          );

        }


        // --------------------------------------------------------
        // CONTENT
        // --------------------------------------------------------

        html += markdownToHtml(content);

        html += `
</div>
`;

      }
    );


    html += `
</div>
`;

  });


  html += `
</body>
</html>
`;

  return html;
}


// ================================================================
// RENDER HTML TO PDF
// ================================================================

async function renderHtmlToPdf(
  html,
  outputPath
) {

  log(
    `Rendering PDF: ${outputPath}`
  );

  let browser = null;

  try {

    log('Launching Puppeteer...');

    browser = await puppeteer.launch({
      headless: true,

      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu'
      ]
    });

    const page =
      await browser.newPage();

    // A4 viewport
    await page.setViewport({
      width: 1240,
      height: 1754,
      deviceScaleFactor: 1
    });

    // ------------------------------------------------------------
    // IMPORTANT
    // ------------------------------------------------------------
    //
    // We use data URIs for images, so there are no external image
    // requests for Puppeteer to resolve.
    //
    // ------------------------------------------------------------

    await page.setContent(
      html,
      {
        waitUntil: 'networkidle0'
      }
    );

    // Give Chromium a moment to finish layout.
    await new Promise(
      resolve => setTimeout(resolve, 300)
    );

    // ------------------------------------------------------------
    // Check images
    // ------------------------------------------------------------

    const imageInfo =
      await page.evaluate(() => {

        const images =
          Array.from(
            document.images
          );

        return {
          count: images.length,

          loaded:
            images.filter(
              img => img.complete && img.naturalWidth > 0
            ).length,

          failed:
            images.filter(
              img => img.complete && img.naturalWidth === 0
            ).length
        };

      });

    log(
      `HTML images: ${imageInfo.count}`
    );

    log(
      `Loaded images: ${imageInfo.loaded}`
    );

    log(
      `Failed images: ${imageInfo.failed}`
    );


    if (imageInfo.count === 0) {

      log(
        '⚠️ No images found in this HTML document.'
      );

    } else if (
      imageInfo.failed > 0
    ) {

      log(
        `⚠️ ${imageInfo.failed} image(s) failed to load.`
      );

    } else {

      log(
        '✅ All images loaded successfully.'
      );

    }


    // ------------------------------------------------------------
    // Generate PDF
    // ------------------------------------------------------------

    await page.pdf({

      path: outputPath,

      format: 'A4',

      printBackground: true,

      preferCSSPageSize: true,

      displayHeaderFooter: false,

      margin: {
        top: '16mm',
        right: '15mm',
        bottom: '18mm',
        left: '15mm'
      }
    });


    // ------------------------------------------------------------
    // Verify output
    // ------------------------------------------------------------

    if (!fs.existsSync(outputPath)) {

      throw new Error(
        `Puppeteer finished but PDF was not created: ${outputPath}`
      );

    }

    const pdfStats =
      fs.statSync(outputPath);

    log(
      `✅ PDF created: ${outputPath}`
    );

    log(
      `PDF size: ${pdfStats.size} bytes`
    );

    return outputPath;

  } finally {

    if (browser) {

      try {

        await browser.close();

      } catch (closeErr) {

        log(
          '⚠️ Error closing Puppeteer:',
          closeErr.message
        );

      }

    }

  }
}


// ================================================================
// BUILD LESSON PDF
// ================================================================

async function buildLessonPdf(
  structure,
  generatedSections,
  images,
  outputPath
) {

  log('========================================');
  log('Building lesson PDF');
  log(
    `Chapter: ${
      structure?.chapter?.title || 'Unknown'
    }`
  );
  log(
    `Lessons: ${
      structure?.lessons?.length || 0
    }`
  );
  log(
    `Output: ${outputPath}`
  );
  log('========================================');


  // --------------------------------------------------------------
  // Diagnostic image listing
  // --------------------------------------------------------------

  if (
    images &&
    typeof images === 'object'
  ) {

    Object.entries(images).forEach(
      ([lessonIndex, lessonImages]) => {

        const count =
          lessonImages &&
          typeof lessonImages === 'object'
            ? Object.keys(lessonImages).length
            : 0;

        log(
          `Lesson ${Number(lessonIndex) + 1} image count: ${count}`
        );

        if (
          lessonImages &&
          typeof lessonImages === 'object'
        ) {

          Object.entries(lessonImages).forEach(
            ([sectionKey, imageSource]) => {

              const resolved =
                resolveImagePath(imageSource);

              log(`  ${sectionKey}:`);
              log(`     source: ${imageSource}`);
              log(
                `     resolved: ${
                  resolved || '(NOT FOUND)'
                }`
              );
              log(
                `     exists: ${
                  resolved
                    ? fs.existsSync(resolved)
                    : false
                }`
              );

            }
          );

        }

      }
    );

  } else {

    log('⚠️ No images object supplied.');

  }


  // --------------------------------------------------------------
  // Build HTML
  // --------------------------------------------------------------

  const html =
    buildLessonHtml(
      structure,
      generatedSections,
      images || {}
    );


  // --------------------------------------------------------------
  // Render
  // --------------------------------------------------------------

  return renderHtmlToPdf(
    html,
    outputPath
  );
}


// ================================================================
// EXPORTS
// ================================================================

module.exports = {
  buildLessonPdf,
  renderHtmlToPdf,
  resolveImagePath,
  markdownToHtml
};